server:
  name: "hcf"

agent:
  key: "something"

database:
  redis:
    host: "localhost"
    port: 6379
    timeout: 2000
    channel: "serverutils"
    auth:
      enabled: false
      password: ""
  mongo:
    host: "localhost"
    port: 27017
    database: "serverutils"
    username: "admin"
    auth:
      enabled: false
      password: ""