name: ServerUtils
main: me.sergivb01.sutils.ServerUtils
version: 1.0
author: sergivb01
commands:
  sc:
  report:
  staffserver:
  test:
  request:
    aliases: [helpop]
  joinqueue:
  leavequeue:
  statusqueue: